import { writeFile, mkdir } from 'fs/promises'
import { join, dirname } from 'path'
import type { ToolDefinition } from '../types'

export const definition: ToolDefinition = {
  name: 'write_update_report',
  description:
    'Generate and save a structured dependency update report. Summarizes all analyzed packages, their changes, breaking changes, and urgency levels into a single actionable markdown report.',
  parameters: {
    type: 'object',
    properties: {
      filename: {
        type: 'string',
        description: 'Filename for the report (e.g. "dependency-report.md")',
      },
      project_name: {
        type: 'string',
        description: 'Name of the project being analyzed',
      },
      summary: {
        type: 'string',
        description: 'High-level summary of the dependency landscape (1-3 sentences)',
      },
      critical_updates: {
        type: 'string',
        description: 'Newline-separated list of critical/high-urgency updates that need immediate attention',
      },
      moderate_updates: {
        type: 'string',
        description: 'Newline-separated list of moderate updates worth doing soon',
      },
      low_updates: {
        type: 'string',
        description: 'Newline-separated list of low-priority updates that can wait',
      },
      breaking_changes: {
        type: 'string',
        description: 'Detailed description of any breaking changes found, with migration steps if available',
      },
      recommendations: {
        type: 'string',
        description: 'Specific recommendations for the update strategy',
      },
    },
    required: ['filename', 'project_name', 'summary', 'recommendations'],
  },
}

export async function execute(args: Record<string, unknown>): Promise<string> {
  const filename = args.filename as string
  const projectName = args.project_name as string
  const summary = args.summary as string
  const criticalUpdates = (args.critical_updates as string) || ''
  const moderateUpdates = (args.moderate_updates as string) || ''
  const lowUpdates = (args.low_updates as string) || ''
  const breakingChanges = (args.breaking_changes as string) || 'None detected'
  const recommendations = args.recommendations as string

  if (!filename || !projectName || !summary || !recommendations) {
    return 'Error: filename, project_name, summary, and recommendations are required'
  }

  const criticalList = criticalUpdates.split('\n').filter(Boolean)
  const moderateList = moderateUpdates.split('\n').filter(Boolean)
  const lowList = lowUpdates.split('\n').filter(Boolean)

  const totalUpdates = criticalList.length + moderateList.length + lowList.length
  const urgencyBadge = criticalList.length > 0 ? '🔴 ACTION REQUIRED' : moderateList.length > 0 ? '🟡 UPDATES AVAILABLE' : '🟢 UP TO DATE'

  const report = `# Dependency Update Report: ${projectName}

## ${urgencyBadge}

**Generated**: ${new Date().toISOString().split('T')[0]}
**Updates found**: ${totalUpdates}

### Summary

${summary}

---

${criticalList.length > 0 ? `## 🔴 Critical / High Priority

These updates should be applied as soon as possible — they may contain security fixes or breaking changes that affect your application.

${criticalList.map(u => `- **${u}**`).join('\n')}
` : ''}
${moderateList.length > 0 ? `## 🟡 Moderate Priority

Worth updating in your next maintenance window.

${moderateList.map(u => `- ${u}`).join('\n')}
` : ''}
${lowList.length > 0 ? `## 🟢 Low Priority

Minor updates, new features, or patches that aren't urgent.

${lowList.map(u => `- ${u}`).join('\n')}
` : ''}
## Breaking Changes

${breakingChanges}

## Recommendations

${recommendations}

---

### Update Strategy

${criticalList.length > 0 ? `1. **Start with critical updates** — apply one at a time, run tests after each
2. **Check breaking changes** above and update your code accordingly
3. **Move to moderate updates** once critical ones are stable
4. **Low-priority updates** can be batched in a maintenance PR` : `1. **Review moderate updates** during your next maintenance window
2. **Batch low-priority updates** together in a single PR
3. **Run your full test suite** after updating`}

---

*Generated by Dependency Changelog Summarizer — an open-source AI agent for understanding your updates*
`

  const sanitized = filename.replace(/[^a-zA-Z0-9._-]/g, '_')
  const outputDir = join(process.cwd(), 'output')
  const filePath = join(outputDir, sanitized)

  try {
    await mkdir(dirname(filePath), { recursive: true })
    await writeFile(filePath, report, 'utf-8')
    return `Report saved to output/${sanitized} (${report.length} characters)\n\nSummary: ${urgencyBadge} — ${totalUpdates} updates found`
  } catch (err) {
    return `Report write error: ${err instanceof Error ? err.message : 'Unknown error'}`
  }
}
