import { writeFile, mkdir } from 'fs/promises'
import { join, dirname } from 'path'
import type { ToolDefinition } from '../types'

export const definition: ToolDefinition = {
  name: 'write_health_report',
  description:
    'Generate and save a structured health report for a GitHub repository. Includes an overall health score (A-F), category scores, strengths, weaknesses, and recommendations.',
  parameters: {
    type: 'object',
    properties: {
      filename: {
        type: 'string',
        description: 'Filename for the report (e.g. "react-health-report.md")',
      },
      repo_name: {
        type: 'string',
        description: 'Full repo name (owner/repo)',
      },
      overall_grade: {
        type: 'string',
        description: 'Overall health grade: A, B, C, D, or F',
      },
      documentation_score: {
        type: 'string',
        description: 'Documentation quality score (1-10) with brief justification',
      },
      maintenance_score: {
        type: 'string',
        description: 'Maintenance/activity score (1-10) with brief justification',
      },
      community_score: {
        type: 'string',
        description: 'Community health score (1-10) with brief justification',
      },
      code_quality_score: {
        type: 'string',
        description: 'Code quality indicators score (1-10) with brief justification',
      },
      strengths: {
        type: 'string',
        description: 'Newline-separated list of repository strengths',
      },
      weaknesses: {
        type: 'string',
        description: 'Newline-separated list of repository weaknesses or concerns',
      },
      recommendations: {
        type: 'string',
        description: 'Specific recommendations for users considering this dependency, or for maintainers improving it',
      },
      summary: {
        type: 'string',
        description: 'One-paragraph executive summary of the repository health',
      },
    },
    required: ['filename', 'repo_name', 'overall_grade', 'documentation_score', 'maintenance_score', 'community_score', 'strengths', 'weaknesses', 'summary'],
  },
}

export async function execute(args: Record<string, unknown>): Promise<string> {
  const filename = args.filename as string
  const repoName = args.repo_name as string
  const overallGrade = args.overall_grade as string
  const docScore = args.documentation_score as string
  const maintScore = args.maintenance_score as string
  const communityScore = args.community_score as string
  const codeScore = (args.code_quality_score as string) || 'N/A'
  const strengths = args.strengths as string
  const weaknesses = args.weaknesses as string
  const recommendations = (args.recommendations as string) || 'See analysis above.'
  const summary = args.summary as string

  if (!filename || !repoName || !overallGrade || !summary) {
    return 'Error: filename, repo_name, overall_grade, and summary are required'
  }

  const gradeEmoji: Record<string, string> = { A: '🟢', B: '🟢', C: '🟡', D: '🟠', F: '🔴' }
  const emoji = gradeEmoji[overallGrade.charAt(0).toUpperCase()] || '⚪'

  const report = `# Repository Health Report: ${repoName}

## ${emoji} Overall Grade: ${overallGrade}

**Generated**: ${new Date().toISOString().split('T')[0]}

### Executive Summary

${summary}

---

## Scores

| Category | Score | Details |
|----------|-------|---------|
| Documentation | ${docScore} | README, guides, API docs |
| Maintenance | ${maintScore} | Commit frequency, release cadence |
| Community | ${communityScore} | Issue response, PRs, contributors |
| Code Quality | ${codeScore} | CI, tests, linting, types |

---

## Strengths

${strengths.split('\n').filter(Boolean).map(s => `- ✅ ${s.trim()}`).join('\n')}

## Weaknesses / Concerns

${weaknesses.split('\n').filter(Boolean).map(w => `- ⚠️ ${w.trim()}`).join('\n')}

## Recommendations

${recommendations}

---

## Should You Use This?

${overallGrade.startsWith('A') ? `**Yes.** This repository shows strong signs of health across all metrics. It's well-maintained, well-documented, and has an active community.` :
overallGrade.startsWith('B') ? `**Probably yes.** This repository is generally healthy with minor areas for improvement. Good for production use with standard due diligence.` :
overallGrade.startsWith('C') ? `**With caution.** This repository has notable gaps. Consider the weaknesses listed above and whether they affect your use case. Have a fallback plan.` :
overallGrade.startsWith('D') ? `**Think twice.** Significant health concerns exist. If you must use this, pin your version, vendor the code, and plan for potential abandonment.` :
`**Not recommended.** This repository shows signs of abandonment or critical issues. Look for alternatives.`}

---

*Generated by Repo Health Scanner — an open-source AI agent for evaluating GitHub repositories*
`

  const sanitized = filename.replace(/[^a-zA-Z0-9._-]/g, '_')
  const outputDir = join(process.cwd(), 'output')
  const filePath = join(outputDir, sanitized)

  try {
    await mkdir(dirname(filePath), { recursive: true })
    await writeFile(filePath, report, 'utf-8')
    return `Health report saved to output/${sanitized} (${report.length} characters)\n\nSummary: ${emoji} Grade ${overallGrade} for ${repoName}`
  } catch (err) {
    return `Report write error: ${err instanceof Error ? err.message : 'Unknown error'}`
  }
}
