import { writeFile, mkdir } from 'fs/promises'
import { join, dirname } from 'path'
import type { ToolDefinition } from '../types'

export const definition: ToolDefinition = {
  name: 'generate_risk_report',
  description:
    'Generate and save a structured scam risk report for a job posting. Takes the analysis results and produces a markdown report with a risk score (1-10), identified red flags, verification results, and recommendations. Saves to the output directory.',
  parameters: {
    type: 'object',
    properties: {
      filename: {
        type: 'string',
        description: 'Filename for the report (e.g. "acme-corp-job-risk.md")',
      },
      job_title: {
        type: 'string',
        description: 'The job title from the posting',
      },
      company_name: {
        type: 'string',
        description: 'The company name from the posting',
      },
      risk_score: {
        type: 'string',
        description: 'Risk score from 1 (very safe) to 10 (almost certainly a scam)',
      },
      red_flags: {
        type: 'string',
        description: 'Newline-separated list of red flags found in the posting',
      },
      green_flags: {
        type: 'string',
        description: 'Newline-separated list of positive/legitimate indicators',
      },
      verification_summary: {
        type: 'string',
        description: 'Summary of employer verification results',
      },
      recommendation: {
        type: 'string',
        description: 'Final recommendation: SAFE / CAUTION / LIKELY SCAM / SCAM',
      },
      details: {
        type: 'string',
        description: 'Detailed analysis explaining the assessment',
      },
    },
    required: ['filename', 'job_title', 'company_name', 'risk_score', 'red_flags', 'recommendation', 'details'],
  },
}

export async function execute(args: Record<string, unknown>): Promise<string> {
  const filename = args.filename as string
  const jobTitle = args.job_title as string
  const companyName = args.company_name as string
  const riskScore = args.risk_score as string
  const redFlags = args.red_flags as string
  const greenFlags = (args.green_flags as string) || 'None identified'
  const verificationSummary = (args.verification_summary as string) || 'Not performed'
  const recommendation = args.recommendation as string
  const details = args.details as string

  if (!filename || !jobTitle || !companyName || !riskScore || !recommendation || !details) {
    return 'Error: filename, job_title, company_name, risk_score, recommendation, and details are all required'
  }

  const score = parseInt(riskScore, 10)
  const riskEmoji = score <= 3 ? '🟢' : score <= 6 ? '🟡' : '🔴'
  const riskLabel = score <= 3 ? 'LOW RISK' : score <= 6 ? 'MODERATE RISK' : 'HIGH RISK'

  const report = `# Job Scam Risk Report

## ${riskEmoji} Risk Score: ${riskScore}/10 — ${riskLabel}

| Field | Value |
|-------|-------|
| **Job Title** | ${jobTitle} |
| **Company** | ${companyName} |
| **Recommendation** | **${recommendation}** |
| **Generated** | ${new Date().toISOString().split('T')[0]} |

---

## Red Flags Found

${redFlags.split('\n').map(f => f.trim()).filter(Boolean).map(f => `- ⚠️ ${f}`).join('\n') || '- None found'}

## Positive Indicators

${greenFlags.split('\n').map(f => f.trim()).filter(Boolean).map(f => `- ✅ ${f}`).join('\n') || '- None identified'}

## Employer Verification

${verificationSummary}

## Detailed Analysis

${details}

---

## What To Do Next

${score <= 3 ? `This posting appears legitimate. Standard precautions apply:
- Research the company independently before your interview
- Never pay money to apply or start a job
- Verify the interviewer's identity via the company's official website` :
score <= 6 ? `Proceed with caution:
- Do NOT share personal financial information (SSN, bank details) until you've verified the company through independent research
- Look up the company on LinkedIn and verify the recruiter works there
- Search for the exact job title + company on the company's official careers page
- If they ask for money or gift cards at any point, it's a scam` :
`This posting has significant scam indicators:
- Do NOT share any personal information
- Do NOT send money, gift cards, or cryptocurrency
- Do NOT download any files or software they send you
- Report this posting to the platform where you found it
- If you've already shared information, monitor your accounts and consider a credit freeze`}

---

*Generated by Job Scam Detector — an open-source AI agent for analyzing job postings*
`

  const sanitized = filename.replace(/[^a-zA-Z0-9._-]/g, '_')
  const outputDir = join(process.cwd(), 'output')
  const filePath = join(outputDir, sanitized)

  try {
    await mkdir(dirname(filePath), { recursive: true })
    await writeFile(filePath, report, 'utf-8')
    return `Risk report saved to output/${sanitized} (${report.length} characters)\n\nSummary: ${riskEmoji} ${riskLabel} (${riskScore}/10) — ${recommendation}`
  } catch (err) {
    return `Report write error: ${err instanceof Error ? err.message : 'Unknown error'}`
  }
}
